# Generated by Django 4.0.2 on 2022-02-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('origine', models.TextField(choices=[('Chaos', 'Chaos'), ('Imperial', 'Imperial'), ('Xeno', 'Xeno')])),
            ],
        ),
    ]
