# Generated by Django 4.0.2 on 2022-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_signup_email_remove_signup_pseudo_signup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='origine',
            field=models.CharField(choices=[('Chaos', 'Chaos'), ('Imperial', 'Imperial'), ('Xeno', 'Xeno')], max_length=10),
        ),
    ]
