# Generated by Django 4.0.2 on 2022-02-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userorigine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signUp',
        ),
    ]
