# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_authentification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrigine',
            new_name='UserOrigin',
        ),
    ]
