# Generated by Django 4.0.2 on 2022-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_userorigine_userorigin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorigin',
            name='name',
        ),
        migrations.AddField(
            model_name='userorigin',
            name='origin',
            field=models.CharField(choices=[('Chaos', 'Chaos'), ('Impérial', 'Imperium'), ('Xeno', 'Xeno')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
