# Generated by Django 4.0.2 on 2022-02-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_userorigin_origin_userorigin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrigin',
        ),
    ]
