# Generated by Django 4.0.2 on 2022-03-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_delete_userorigin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentification',
        ),
    ]
