# Generated by Django 4.0.2 on 2022-03-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_charactersmodel_delete_charactermodel'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chaosAspectVenerated',
        ),
    ]
