# Generated by Django 4.0.2 on 2022-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationrace',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
