# Generated by Django 4.0.2 on 2022-03-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_chaosaspectvenerated_creationrace_creationside_and_more'),
        ('main', '0004_alter_creationrace_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chaosAspectVenerated',
        ),
        migrations.DeleteModel(
            name='creationRace',
        ),
        migrations.DeleteModel(
            name='creationSide',
        ),
        migrations.DeleteModel(
            name='creationType',
        ),
    ]
