# Generated by Django 4.0.2 on 2022-04-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheca', '0004_rename_articlename_histoiry_articlecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histoiry',
            old_name='title',
            new_name='articletitle',
        ),
    ]
