# Generated by Django 4.0.2 on 2022-04-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheca', '0006_rename_articlecontent_histoiry_articlename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histoiry',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotheca.histoiry'),
        ),
    ]
