# Generated by Django 4.0.2 on 2022-04-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheca', '0008_rename_articlename_histoiry_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='histoiry',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='content',
            new_name='contentURL',
        ),
    ]
