# Generated by Django 4.0.2 on 2022-03-02 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='characterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('Personnel', 'Personnel'), ('Historique', 'Historique')], max_length=50)),
                ('side', models.CharField(choices=[('Imperium', 'Imperium'), ('Chaos', 'Chaos'), ('Xeno', 'Xeno')], max_length=50)),
                ('race', models.CharField(choices=[('Space Marine', 'Spacemarine'), ('Custodes', 'Custodes'), ('Garde Imperial', 'Imperialguard'), ('Adeptus Mechanicus', 'Mechanicum'), ('Chevalier Impérial', 'Imperialknight'), ('Soeur de bataille', 'Battlesister'), ('Space Marine du chaos', 'Chaosspacemarine'), ('Demon', 'Demon'), ('Garde Renégat', 'Renegadeguard'), ('Chevalier du chaos', 'Renagadeknight'), ('Ork', 'Ork'), ('Aeldari', 'Aeldari'), ('Drukhari', 'Drukhari'), ('Tau', 'Tau')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chaosAspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chaosaspectvenerated')),
            ],
        ),
    ]
