# Generated by Django 4.0.2 on 2022-03-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chaosAspectVenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='creationRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='creationSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='charactersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historicCreation', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(max_length=10000)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='community\\characterspictures')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chaosAspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.chaosaspectvenerated')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationrace')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationside')),
                ('speciality', models.ManyToManyField(to='community.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='armyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historicCreation', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('history', models.TextField(max_length=10000)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='community\\characterspictures')),
                ('actualChef', models.CharField(max_length=50)),
                ('firstChef', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chaosAspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.chaosaspectvenerated')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationrace')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationside')),
                ('speciality', models.ManyToManyField(to='community.speciality')),
            ],
        ),
    ]
