# Generated by Django 4.0.2 on 2022-03-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_creationrace_side_alter_armymodel_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationrace',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationside'),
        ),
    ]
