# Generated by Django 4.0.2 on 2022-03-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_creationrace_side'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creationRace',
            new_name='Races',
        ),
        migrations.RenameModel(
            old_name='creationSide',
            new_name='Side',
        ),
    ]
