# Generated by Django 4.0.2 on 2022-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_charactersmodel_delete_charactermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='chaosAspect',
            field=models.CharField(blank=True, choices=[('undivided', 'Universel'), ('khorn', 'Khorn'), ('nurgle', 'Nurgle'), ('tzeentch', 'Tzeentch'), ('slannesh', 'Slannesh')], max_length=50, null=True),
        ),
    ]
