# Generated by Django 4.0.2 on 2022-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_charactersmodel_chaosaspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='race',
            field=models.CharField(choices=[('spaceMarine', 'Space Marine'), ('custodes', 'Adeptus Custodes'), ('astraMilitarum', 'Astra Militarum'), ('adeptusMechanicus', 'Adeptus Mechanicus'), ('imperialKnight', 'Chevalier Impérial'), ('battleSister', 'Soeur de bataille'), ('chaosSpaceMarine', 'Space Marine du chaos'), ('demon', 'Démon du chaos'), ('chaosCultiste', 'Cultiste du Chaos'), ('renagadeKnight', 'Chevalier du Chaos'), ('ork', 'Ork'), ('aeldari', 'Aeldari'), ('drukhari', 'Drukhari'), ('tau', 'Tau')], max_length=50),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='side',
            field=models.CharField(choices=[('imperium', 'Imperium'), ('chaos', 'Chaos'), ('xeno', 'Xeno')], max_length=50),
        ),
    ]
