# Generated by Django 4.0.2 on 2022-03-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_charactersmodel_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='chaosAspect',
            field=models.CharField(blank=True, choices=[('undivided', 'Universel'), ('Khorn', 'Khorn'), ('Nurgle', 'Nurgle'), ('Tzeentch', 'Tzeentch'), ('Slannesh', 'Slannesh')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='race',
            field=models.CharField(choices=[('Space Marine', 'Space Marine'), ('Adeptus Custodes', 'Adeptus Custodes'), ('Astra Militarum', 'Astra Militarum'), ('Adeptus Mechanicus', 'Adeptus Mechanicus'), ('Chevalier Impérial', 'Chevalier Impérial'), ('Soeur de bataille', 'Soeur de bataille'), ('Space Marine du chaos', 'Space Marine du chaos'), ('demon', 'Démon du chaos'), ('Cultiste du Chaos', 'Cultiste du Chaos'), ('Chevalier du Chaos', 'Chevalier du Chaos'), ('Ork', 'Ork'), ('Aeldari', 'Aeldari'), ('Drukhari', 'Drukhari'), ('Tau', 'Tau')], max_length=50),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='side',
            field=models.CharField(choices=[('Imperium', 'Imperium'), ('Chaos', 'Chaos'), ('Xeno', 'Xeno')], max_length=50),
        ),
    ]
