# Generated by Django 4.0.2 on 2022-03-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
        ('community', '0008_alter_charactersmodel_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='chaosAspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chaosaspectvenerated'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creationrace'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creationside'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creationtype'),
        ),
    ]
