# Generated by Django 4.0.2 on 2022-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_charactersmodel_chaosaspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersmodel',
            name='biography',
            field=models.TextField(max_length=10000),
        ),
    ]
