# Generated by Django 4.0.2 on 2022-03-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_armymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='charactersmodel',
            name='chaosAspect',
        ),
        migrations.RemoveField(
            model_name='charactersmodel',
            name='race',
        ),
        migrations.RemoveField(
            model_name='charactersmodel',
            name='side',
        ),
        migrations.RemoveField(
            model_name='charactersmodel',
            name='type',
        ),
        migrations.DeleteModel(
            name='armyModel',
        ),
        migrations.DeleteModel(
            name='charactersModel',
        ),
    ]
