# Generated by Django 4.0.2 on 2022-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armymodel',
            name='history',
            field=models.TextField(max_length=10000),
        ),
    ]
