# Generated by Django 4.0.2 on 2022-03-10 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_alter_armymodel_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='chaosAspectVenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='creationRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='creationSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='armymodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='charactersmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='armymodel',
            name='historicArmy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charactersmodel',
            name='characterArmy',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='armymodel',
            name='speciality',
        ),
        migrations.AddField(
            model_name='charactersmodel',
            name='speciality',
            field=models.ManyToManyField(to='community.speciality'),
        ),
        migrations.AlterField(
            model_name='armymodel',
            name='chaosAspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.chaosaspectvenerated'),
        ),
        migrations.AlterField(
            model_name='armymodel',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationrace'),
        ),
        migrations.AlterField(
            model_name='armymodel',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationside'),
        ),
        migrations.AddField(
            model_name='armymodel',
            name='speciality',
            field=models.ManyToManyField(to='community.speciality'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='chaosAspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.chaosaspectvenerated'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationrace'),
        ),
        migrations.AlterField(
            model_name='charactersmodel',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.creationside'),
        ),
    ]
