# Generated by Django 4.0.2 on 2022-03-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_chaosaspectvenerated_creationrace_creationside_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armymodel',
            old_name='historicArmy',
            new_name='historicCreation',
        ),
        migrations.RenameField(
            model_name='charactersmodel',
            old_name='characterArmy',
            new_name='historicCreation',
        ),
        migrations.RemoveField(
            model_name='armymodel',
            name='speciality',
        ),
        migrations.AddField(
            model_name='armymodel',
            name='speciality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
