# Generated by Django 4.0.2 on 2022-03-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_rename_historicarmy_armymodel_historiccreation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armymodel',
            name='speciality',
        ),
        migrations.AddField(
            model_name='armymodel',
            name='speciality',
            field=models.ManyToManyField(to='community.speciality'),
        ),
    ]
